version: '3'
services:

  loki:
    image: grafana/loki:2.9.0
    container_name: loki-bank
    ports:
      - 3100:3100
    volumes:
      - ./loki/config/loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail-bank
    volumes:
      - ./paypal-back/logs:/var/logs
      - ./promtail/config/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana-bank
    restart: unless-stopped
    user: "root"
    ports:
      - 3000:3000
    links:
      - loki:loki
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug
      - GF_PLUGINS_ENABLE_ALPHA=true
    depends_on:
      - loki

volumes:
  grafana:
  loki:
  prometheus:
