scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8085']
